version: '3'
services:
  migrate:
    build:
      context: .
      dockerfile: migrationDockerfile
    depends_on:
      - postgres
    env_file: docker.env
    command: npx prisma migrate deploy

  # app:
  #   build:
  #     context: .
  #     dockerfile: appDockerfile
  #   env_file: docker.env
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #     - minio


  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: '${PG_USER:-root}'
      POSTGRES_PASSWORD: '${PG_PASSWORD:-password}'
      POSTGRES_DB: '${PG_DATABASE:-files}'
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data/
    ports:
      - '${PG_PORT:-5432}:5432/tcp'

  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: '${AWS_ACCESS_KEY:-root}'
      MINIO_ROOT_PASSWORD: '${AWS_SECRET:-password}'
    volumes:
      - './data/minio/data:/data/minio'
    command: minio server /data/minio --console-address ":9090"
